### ISSUE TITLE
插件在 halo2.x 后台启用后怎么使用

### ISSUE THREAD

**Issue by qiushaocloud** [guqing/plugin-metrics-graph#3]
插件在 halo2.x 后台启用后怎么使用，启用后界面没什么不同的，麻烦出个教程

**Comment by guqing** [comment]
安装并启动插件之后会多出如下`指标监控`菜单项
<img width="275" alt="image" src="https://github.com/guqing/plugin-metrics-graph/assets/38999863/ac2533af-679f-428e-832d-8db94d5909b1">
